fixtures:
  repositories:
    ssh:
      repo: https://github.com/saz/puppet-ssh.git
      ref: v3.0.1
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: 2.2.1
